"""Added notes and external link to TimeRecord

Revision ID: 1465dbfdc12f
Revises: 
Create Date: 2025-10-20 11:13:04.506897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1465dbfdc12f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('external_link')

    # ### end Alembic commands ###
