"""Add JIRA integration tables and fields

Revision ID: 9cbce0c77344
Revises: 1465dbfdc12f
Create Date: 2026-01-29 11:39:49.545341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cbce0c77344'
down_revision = '1465dbfdc12f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jira_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jira_url', sa.String(length=255), nullable=False),
    sa.Column('auth_type', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('api_token_encrypted', sa.Text(), nullable=True),
    sa.Column('oauth_access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('oauth_refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jira_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_record_id', sa.Integer(), nullable=False),
    sa.Column('jira_issue_key', sa.String(length=50), nullable=False),
    sa.Column('jira_worklog_id', sa.String(length=50), nullable=True),
    sa.Column('sync_status', sa.String(length=20), nullable=False),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.Column('synced_by_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['synced_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['time_record_id'], ['time_record.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('jira_issue_key', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('jira_worklog_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('jira_synced', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('jira_sync_error', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('last_synced_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_record', schema=None) as batch_op:
        batch_op.drop_column('last_synced_at')
        batch_op.drop_column('jira_sync_error')
        batch_op.drop_column('jira_synced')
        batch_op.drop_column('jira_worklog_id')
        batch_op.drop_column('jira_issue_key')

    op.drop_table('jira_sync_log')
    op.drop_table('jira_connection')
    # ### end Alembic commands ###
